Remove `CONTARINER_NAME` variable from run.sh
aiidalab/aiidalab-docker-stack pull request #203
Opened 2021-09-15 20:18 UTC by yakutovicha

The containers must always have different name, otherwise they
wouldn't start.

2021-09-15 21:55 UTC, ltalirz commented
This was done in response to a request by @mbercx , see https://github.com/aiidalab/aiidalab-docker-stack/issues/183

In his use case, I guess only one container is ever needed at a given time.

Is the `./run.sh` also used by the jupyterhub installations?

Perhaps we could add a `--name` argument to the runscript that names the container only if specified.

2021-09-16 07:35 UTC, csadorf requested changes
The use case of starting multiple containers appears less safe and likely to me than explicitly setting a different name when desired. What happens when both containers mount the same home directory?

I would instead suggest to make the name an optional parameters which a user can set to a different value when desired, e.g., when they want to start more than one container.

2021-09-16 08:36 UTC, yakutovicha commented
> The use case of starting multiple containers appears less safe and likely to me than explicitly setting a different name when desired

I think I didn't explain the issue properly. The thing is: even if the container with "aiidalab" name is stopped, starting another one with the same name wouldn't be possible.

2021-09-16 08:38 UTC, ltalirz commented
> I think I didn't explain the issue properly. The thing is: even if the container with "aiidalab" name is stopped, starting another one with the same name wouldn't be possible.

You just explain to people that they remove the container with `docker rm -f aiidalab` , see https://github.com/aiidalab/aiidalab/pull/214

2021-09-16 08:42 UTC, csadorf commented
As I had pointed out before, I would suggest that we adopt the aiidalab-docker-stack-demo model with a docker-compose.yml and control script. It's more easily configurable and avoids a lot of these issues or at least makes them easier to deal with.

2021-09-16 08:48 UTC, ltalirz commented
I've had a look at the repo docker-stack-demo and the docker-compose approach looks good to me.

Ideally, we could maintain that here in the docker-stack repo; switching to the docker-stack-demo should then just be changing one variable.

2021-09-16 09:00 UTC, yakutovicha commented
Thanks to both. I agree that we should probably adopt the docker-compose approach here. I also agree that when running multiple containers at the same time user should be requested to provide a new name explicitly.

The only thing I would like to comment on is this statement:

> You should only stop the container if you plan restarting it.

I sometimes stop the containers when the machine is overloaded or I just switch off my computer. The only thing I would like to avoid is a message like "Sorry, I cannot start the 'aiidalab' container" because it already exists.

2021-10-21 13:34 UTC, yakutovicha commented
superseded by #217

2021-10-21 13:34 UTC, closed without merging